# Generated by Django 4.1 on 2022-09-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoparks', '0001_initial'),
        ('cars', '0004_alter_carmodel_brand_alter_carmodel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='auto_park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autoparks.autoparkmodel'),
            preserve_default=False,
        ),
    ]
